server:
  port: 8087
application:
  security:
    redis-enabled: false
    ip-lock:
      enabled: false
      max-attempts: ${SECURITY_MAX_ATTEMPTS:3}
      lock-time-minutes: ${SECURITY_LOCK_TIME:5}
    jwt:
      secret-key: McvbIKwPaVjhmKBwFUdHDXzvfWeAZgaJ8XJr6cBsvNkPI9VUvAWw7GzFMV6ZhHsI
      expiration: 315360000000
      refresh-token:
        expiration: 315360000000

spring:
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    url: jdbc:postgresql://postgres:5432/appdb
    username: app
    password: apppass
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        envers:
          audit_table_suffix: _aud

          store_data_at_delete: true

